export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REDIRECT_PATH='AUTH_REDIRECT_PATH';

export const FETCHING_STORY_START='FETCHING_STORY_START';
export const FETCHING_STORY_FAIL='FETCHING_STORY_FAIL';
export const FETCHING_STORY_SUCCESS='FETCHING_STORY_SUCCESS';

export const POSTING_STORY_START='POSTING_STORY_START';
export const POSTING_STORY_FAIL='POSTING_STORY_FAIL';
export const POSTING_STORY_SUCCESS='POSTING_STORY_SUCCESS';

export const MODAL_CLOSE='MODAL_CLOSE';
export const MODAL_OPEN='MODAL_OPEN';

export const FETCH_USER_STORY_START='FETCH_USER_STORY_START';
export const FETCH_USER_STORY_FAIL='FETCH_USER_STORY_FAIL';
export const FETCH_USER_STORY_SUCCESS='FETCH_USER_STORY_SUCCESS';

export const FETCH_USER_DATA_START='FETCH_USER_DATA_START';
export const FETCH_USER_DATA_SUCCESS='FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAIL='FETCH_USER_DATA_FAIL';


export const UPDATED_STORY='UPDATED_STORY';
export const ADDED_STORY='ADDED_STORY';
export const DELETED_STORY='DELETED_STORY';
export const UPDATED_PROFILE='UPDATED_PROFILE';

// export const DELETING_STORY_START='DELETING_STORY_START';
// export const DELETING_STORY_FAIL='DELETING_STORY_FAIL';
// export const DELETING_STORY_SUCCESS='DELETING_STORY_SUCCESS';

// export const FETCHING_USER_PROFILE_START='FETCHING_USER_PROFILE_START';
// export const FETCHING_USER_PROFILE_FAIL='FETCHING_USER_PROFILE_FAIL';
// export const FETCHING_USER_PROFILE_SUCCESS='FETCHING_USER_PROFILE_SUCCESS';

